### ISSUE TITLE
add dist in npm package or git tag

### ISSUE THREAD

**Issue by maruilian11** [Autarc/optimal-select#11]
hi, recently we want to add your lib to https://cdnjs.com, could you please also add `dist` in npm package or add git tag for each released version. that will help us use **npm auto-update** or **git auto-update** to update your lib on cdnjs.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/8066

**Comment by Autarc** [comment]
Thanks for putting it up :+1: 

Just published the latest version at npm which includes the `dist` directory. In addition the git repository now also contains a tagged version, which should ease the integration.

**Comment by maruilian11** [comment]
thanks a lot!
