### ISSUE TITLE
Unminified dist is minified

### ISSUE THREAD

**Issue by TrueWill** [Autarc/optimal-select#12]
https://github.com/Autarc/optimal-select/blob/master/dist/optimal-select.js is minified. It should be the unminified version.

**Comment by Autarc** [comment]
Yeah, thought the regular version for debugging should only reference the sourcemap.  But its probably best to keep an unminified version for simple intergration around. Changed the build configuration in the [last update](https://github.com/Autarc/optimal-select/commit/a3ed99d9ad42a29d3bfeba3fc7f15cf83a2477cb) and should be available now.
