### ISSUE TITLE
bug: cannot read property trim of null

### ISSUE THREAD

**Issue by gebrits** [Autarc/optimal-select#17]
Found a bug "cannot read property trim of nul" on this [line](https://github.com/Autarc/optimal-select/blob/3662acc924b4f6c7abf3c325c91cd41a703d53a1/src/common.js#L79)

**Comment by Autarc** [comment]
Thanks for mention it. Just got fixed through first [checking if the class attribute is available](https://github.com/Autarc/optimal-select/commit/0d6d3f4b07bc1425e3f16b88b9e47f88d61e6197).

**Comment by gebrits** [comment]
cheers!
