### ISSUE TITLE
optimal-select include messes with stacktrace due to double webpack bundling? 

### ISSUE THREAD

**Issue by gebrits** [Autarc/optimal-select#19]
Excuse this brainfart post, but I'm having a weird problem: 

I'm including optimal-select the 'npm way', which is bundled in 1 `bundle.js` using webpack-dev-server when developing. 

This works fine, until I'm having errors in my own code. 
When debugging using chrome devtools, as usual I click on an error to jump to the place in code (in the bundled JS) where the error happens. 

Since including 'optimal-select' the console doesn't jump to the correct place anymore. Instead it always jumps to the end of the `optimal-select/dist/optimal-select.js` file, instead of my `bundle.js` where the error occurs. 

Weird right?  Any guesses to why this might happen? 

One thing I'm thinking here is that  `optimal-select/dist/optimal-select.js` is already a 'webpackified' bundle, which courtesy of an include is packaged again in my own code. Could such nested packing cause the issue? Perhaps I would probably be better of just including the `optimal-select/lib/index.js` because I will be packing it in a webpack bundle anyway.

Any clue how I would go about pointing my webpack config to include `optimal-select/lib/index.js` as entrypoint when doing `require("optimal-select")` instead of defaulting to `optimal-select/dist/optimal-select.js` "

**Comment by venkatkarun** [comment]
You can use an [alias](https://webpack.github.io/docs/configuration.html#resolve-alias) in your webpack configuration like:

```js
module.exports = {
  resolve: {
    alias: {
      'optimal-select': 'optimal-select/lib/index.js',
      .....
    }
  }
}
```

**Comment by gebrits** [comment]
Thanks got this to work the other way around.

```
module.exports = {
  resolve: {
    alias: {
      'optimal-select': "optimal-select/dist/optimal-select.js"
      .....
    }
  }
}
```

Still very weird. Also had to do with rerunning my webpack-dev-server. 
Anyway, don't think it's related to optimal-select so closing here. 

Thanks for pointing me to `alias`. 👍

**Comment by Autarc** [comment]
Is there a reason for not requiring the module the regular way ? By default the distributed version via npm contains the already transpiled files of the source and points to [`lib/index.js`](https://github.com/Autarc/optimal-select/blob/master/package.json#L36). Although pre-bundled versions are included for direct linking, its recommend to just use the module and let your built tools (e.g. webpack or browserify) handle further optimizations at the end.

**Comment by gebrits** [comment]
Yeah I realise that. As I said, I've got a weird problem if I do. I've only ever seen this happen with optimal-select. This doesn't mean that's the culprit it could just be bad luck. 

So when I do it the normal way I get the following issue: See attached screenshot: basically the console is reporting every console.log / stacktrace, etc. happening at commons.jsL147 (the commons.js from optional-select)


<img width="1276" alt="screen shot 2016-10-28 at 23 52 42" src="https://cloud.githubusercontent.com/assets/393259/19823647/0d9336ca-9d6a-11e6-8f9e-8e1cfa928b5a.png">

For completeness: adding the alias to point to the dist version, solves the issue. All stuff now points to the correct lines

<img width="1256" alt="screen shot 2016-10-28 at 23 58 12" src="https://cloud.githubusercontent.com/assets/393259/19823713/7c50c8de-9d6a-11e6-97e6-5f30235aa43e.png">
: 

Thoughts?

**Comment by gebrits** [comment]
One thing that came to mind is that `common.js` has some special meaning in webpack: i.e.: creating a common-package from vendor libraries that are unrelated to a specific page. 

I thought perhaps that interfered in some way. Renamed the package locally to `utils.js` instead. Alas, same issue.

**Comment by Autarc** [comment]
Which webpack version are you using ? So far I `optimal-select` worked fine with the latest stable (1.13.0).

Since the `datalist` property isn't accessed directly by the library it could also be useful to know which other modules are used that might invoke the error.

**Comment by gebrits** [comment]
webpack 1.13.2
webpack-dev-server 1.16.1

somehow think it's more related to how webpacl-dev-server serves it up, but
don't ask my why.
Anyway, I might update those versions when I have the time.
For now I'll close since I'm pretty sure it's not related to
optimal-select.
If/When I find a solution I'll let you know.
