### ISSUE TITLE
Bug - Cannot read property 'length' of null

### ISSUE THREAD

**Issue by steppefox** [Autarc/optimal-select#24]
For the element:

```
<h2 class="screen-reader-text sr-only" role="navigation" itemscope itemtype="http://schema.org/SiteNavigationElement">
Menu</h2>
```

Library throws error in the function `optimizePart`. 

That function receives variable `current` equals `h2.screen-reader-text.sr-only[role="navigation"][itemscope=""][itemtype="http://schema.org/SiteNavigationElement"]`, and throws error here:

https://github.com/Autarc/optimal-select/blob/master/src/optimize.js#L140

```
if (current && current.match(/\./g).length > 2) {
```

If `current` exists, but match regex doesn't return anything, it fails =(

**Comment by autarc** [comment]
Good catch. The reference check [got fixed](https://github.com/Autarc/optimal-select/commit/5db4c09e66fe89727f5e7d10431abb6fb7abf04d#diff-1a13d5f99208e1b7b5dd5e5b6b749e69R143) in the latest version.
