### ISSUE TITLE
Match line breaking attribute values

### ISSUE THREAD

**Issue by Autarc** [Autarc/optimal-select#3]
![line-breaking-attribute-value](https://cloud.githubusercontent.com/assets/1060490/13566887/2d017830-e458-11e5-8be3-fea526dac22b.png)
Complex attribute values which contain a line break won't be matched and instead throw an error.

**Comment by LowWeiLin** [comment]
Line breaks can be replaced by \A to be escaped.

**Comment by Autarc** [comment]
@LowWeiLin Thanks for the advice. Got [now fixed](https://github.com/Autarc/optimal-select/commit/649a1d950b47196b332f5f13961a9c212c751ada) with the latest version.
