### ISSUE TITLE
use with Rollup

### ISSUE THREAD

**Issue by zewa666** [Autarc/optimal-select#34]
I'm trying to require optimal-select as a dependency for Rollup to create an IIFE bundle. rollup-plugin-node-resolve in combination with rollup-plugin-commonjs is not able to bundle it as with the given examples. I tinkered around but still hadn't managed to get to a solution. Anybody has an idea how to get it working?

A minimalistic example like this was my main.js entry
```
import { select } from 'optimal-select' // global: 'OptimalSelect'

document.addEventListener('click', (e) => {
  var selector = select(e.target)
  console.log(selector)  
})
```

**Comment by zewa666** [comment]
ok the issue was an out-of-date rollup version

**Comment by ethanroday** [comment]
@zewa666 What was your fix here? I'm trying to get this working with the latest version of Rollup (0.51.5) and Rollup can't seem to find the module. Here's my config:
```
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
  input: 'index.js',
  output: {
    file: 'bundle.js',
    format: 'iife'
  },
  plugins: [
    nodeResolve(),
    commonjs()
  ]
}
```
And the contents of `index.js` are exactly the same as your example above. Here's what Rollup says:
```
index.js → bundle.js...
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
optimal-select (imported by index.js)
(!) Missing global variable name
Use options.globals to specify browser global variable names corresponding to external modules
optimal-select (guessing 'optimalSelect')
created bundle.js in 44ms
```

**Comment by ethanroday** [comment]
I've also tried with `nodeResolve({
      jsnext: true,
      main: true,
      browser: true
    })`, but I get the same issue.

**Comment by ethanroday** [comment]
Update: If I pass the `module: false` option to `rollup-plugin-node-resolve`, it works just fine. Of course, I would rather not have to do that across the board. @Autarc, could this have something to do with the fact that the `module` field in `optimal-select`'s `package.json` points to source code (`src/index.js`) that is not actually included in the npm dist?

**Comment by ethanroday** [comment]
@Autarc I can confirm that removing the `"module": "src/index.js"` line from `package.json` fixes the problem. I can also confirm that version 3.5.0, the last version without that line (as far as I can tell) does not suffer from this issue.

**Comment by GMCoder** [comment]
> @Autarc I can confirm that removing the `"module": "src/index.js"` line from `package.json` fixes the problem. I can also confirm that version 3.5.0, the last version without that line (as far as I can tell) does not suffer from this issue.

Can you show me your rollup.config.js code?I have the same problem.Thank you!
