### ISSUE TITLE
Using in static contexts

### ISSUE THREAD

**Issue by aas395** [Autarc/optimal-select#38]
Hi,

I'm trying to create a Chrome extension that uses a selector engine like this and I'm wondering if I would be able to use this as a static script rather than including it via Node. I tried a couple of things that didn't seem to work -- could you let me know if this is possible and if so, how I would use your library in a static context?

**Comment by cmincarelli** [comment]
@aas395  this is super easy to do -

```
<!DOCTYPE html>
<html>
<body>
  <ul>
    <li>One</li>
    <li>Two</li>
  </ul>
<script
  type="text/javascript"
  src="https://cdn.jsdelivr.net/npm/optimal-select@4.0.1/dist/optimal-select.js">
</script>
<script type="text/javascript">
  var body = OptimalSelect.getSingleSelector(document.querySelector('body'));
  var li = OptimalSelect.getMultiSelector(document.querySelectorAll('li'));
  console.log(1, body, 2, li);
</script>
</body>
</html>
```

**Comment by aas395** [comment]
Got it, thanks so much for your help!
