### ISSUE TITLE
Add support for wildcard keys

### ISSUE THREAD

**Issue by venkatkarun** [Autarc/optimal-select#5]
For persisting a selector, excluding all HTML5 data attributes is an important pre-requisite for the client library I'm writing. Would you be ok with a startsWith or regex check for the attribute name itself in compareExcludes? Adding support for a predicate function allows the greatest flexibility. Thoughts?

**Comment by Autarc** [comment]
The latest version (2.1) uses now a different filtering scheme. Instead of just comparing attribute values with a provided regex, you can now define a custom validation function which can access the name as well. In your case the following configuration should help:
```js
var selector = select(element, {
  ignore: {
    attribute (name, value, defaultPredicate) {
      return (/data-*/).test(name) || defaultPredicate(name, value)
    }
  }
})
```

**Comment by venkatkarun** [comment]
very cool, thanks for reaching out.
